# Server configuration
server.port=8080

# Logging
logging.level.com.sprih_assignment=INFO
logging.level.org.springframework=WARN

# Swagger/OpenAPI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha